In [22]:
import math
import timeit

import cvxpy as cp
import scipy as sp
import numpy as np
import pickle

In [23]:
cp.installed_solvers()

['CLARABEL',
 'CVXOPT',
 'ECOS',
 'ECOS_BB',
 'GLPK',
 'GLPK_MI',
 'HIGHS',
 'MOSEK',
 'OSQP',
 'PIQP',
 'PROXQP',
 'SCIP',
 'SCIPY',
 'SCS',
 'SDPA']

In [24]:
N = 100
M = 100
max_assigned = math.ceil(N / M)
np.random.seed(0)
X0 = np.zeros((N, M))
W = sp.stats.lognorm.rvs(s=1, size=(N, M))
W

array([[ 5.83603919,  1.49205924,  2.66109578, ...,  5.96476998,
         1.13531721,  1.49479543],
       [ 6.57418553,  0.25982185,  0.28069545, ...,  2.27846997,
         8.69924247,  3.80580659],
       [ 0.69129969,  0.78711637,  3.00314357, ...,  1.79132161,
         0.67068947,  1.44781553],
       ...,
       [ 0.94625443,  1.13956091,  1.55378061, ...,  2.64377323,
         0.39893752,  1.94107219],
       [ 0.87503499,  0.20880169,  0.17400845, ...,  1.07341762,
        11.42413823,  2.6423831 ],
       [ 0.39338669, 17.55262551,  0.16661859, ...,  1.67677479,
         0.9676153 ,  3.66237349]], shape=(100, 100))

In [25]:
x = cp.Variable((N, M), 'x')
w = cp.Parameter((N, M), name='w')
constraints = [
    cp.sum(x, 0) <= max_assigned,   # enforce even distribution
    cp.sum(x, 1) == 1,
    0 <= x,
]
problem = cp.Problem(cp.Minimize(cp.vdot(w, x)), constraints)

# test and compile
def solve_cvxpy(solver, wv):
    x.value = X0
    w.value = wv
    problem.solve(solver=solver,
                  requires_grad=False,
                  ignore_dpp=True,
                  canon_backend=cp.SCIPY_CANON_BACKEND)
    return x.value

solve_cvxpy("ECOS", W).argmax(1)

array([33, 40, 78, 34, 22, 89, 51, 35, 50, 13, 39, 29, 56, 97, 46, 83, 63,
       86, 90, 11, 18, 14, 54, 60, 72,  7, 92,  0,  6, 48, 20, 24,  3, 70,
       62, 45, 79, 52, 53, 12,  9, 21, 38, 37, 69, 82, 74, 93, 49, 10, 23,
       91, 31, 28, 57, 94, 85, 76,  4, 26, 15, 64, 47, 55, 44, 30,  5, 27,
       84, 61, 65,  1, 19, 25, 32, 77, 95, 98, 99, 80, 42, 75, 16, 73, 59,
       17, 41, 81, 87, 71, 96, 88, 43, 36, 58, 68, 66, 67,  8,  2])

In [26]:
A_ub = np.tile(np.identity(M), (1, N))
b_ub = np.full(M, max_assigned)

A_eq = np.repeat(np.identity(N), M, axis=1)
b_eq = np.full(N, 1.0)

c = W.flatten()

In [27]:
def solve_highs():
    return sp.optimize.linprog(
        c=c,
        A_ub=A_ub,
        b_ub=b_ub,
        A_eq=A_eq,
        b_eq=b_eq,
        method="highs",
    ).x.reshape((N, M))
solve_highs().argmax(1)

array([33, 40, 78, 34, 22, 89, 51, 35, 50, 13, 39, 29, 56, 97, 46, 83, 63,
       86, 90, 11, 18, 14, 54, 60, 72,  7, 92,  0,  6, 48, 20, 24,  3, 70,
       62, 45, 79, 52, 53, 12,  9, 21, 38, 37, 69, 82, 74, 93, 49, 10, 23,
       91, 31, 28, 57, 94, 85, 76,  4, 26, 15, 64, 47, 55, 44, 30,  5, 27,
       84, 61, 65,  1, 19, 25, 32, 77, 95, 98, 99, 80, 42, 75, 16, 73, 59,
       17, 41, 81, 87, 71, 96, 88, 43, 36, 58, 68, 66, 67,  8,  2])

In [28]:
A_ub_sparse = sp.sparse.csr_matrix(A_ub)
A_eq_sparse = sp.sparse.csr_matrix(A_eq)

In [29]:
def solve_interior_point():
    return sp.optimize.linprog(
        c=c,
        A_ub=A_ub,
        b_ub=b_ub,
        A_eq=A_eq,
        b_eq=b_eq,
        method="interior-point",
        options=dict(sparse=True),
    ).x.reshape((N, M))
solve_interior_point().argmax(1)

C:\Users\volke\AppData\Local\Temp\ipykernel_26908\3670224332.py:2: DeprecationWarning: `method='interior-point'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  return sp.optimize.linprog(


array([33, 40, 78, 34, 22, 89, 51, 35, 50, 13, 39, 29, 56, 97, 46, 83, 63,
       86, 90, 11, 18, 14, 54, 60, 72,  7, 92,  0,  6, 48, 20, 24,  3, 70,
       62, 45, 79, 52, 53, 12,  9, 21, 38, 37, 69, 82, 74, 93, 49, 10, 23,
       91, 31, 28, 57, 94, 85, 76,  4, 26, 15, 64, 47, 55, 44, 30,  5, 27,
       84, 61, 65,  1, 19, 25, 32, 77, 95, 98, 99, 80, 42, 75, 16, 73, 59,
       17, 41, 81, 87, 71, 96, 88, 43, 36, 58, 68, 66, 67,  8,  2])

In [41]:
exclude_solvers = {
    "CVXOPT",
    "MOSEK",    # requires license
    "SCS",
    "PIQP",
    "SCIP",
    "SDPA",
    "GLPK",
    "PDLP",
    "OSQP",
    "PROXQP",
}
solvers = sorted(set(cp.installed_solvers()) - exclude_solvers)
n = 16
for solver in solvers:
    print(solver, end="\t")
    solve_cvxpy(solver, W)
    wv = sp.stats.lognorm.rvs(s=1, size=(N, M))
    print(1000 * timeit.timeit(lambda: solve_cvxpy(solver, wv), number=n) / n)

CLARABEL	55.37041249772301
ECOS	41.032393753994256
ECOS_BB	40.29933750280179
GLPK_MI	104.06780624907697
HIGHS	43.32822500145994
SCIPY	30.92369999649236


In [42]:
%%timeit
solve_highs()

30 ms ± 1.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
%%timeit
solve_interior_point()

C:\Users\volke\AppData\Local\Temp\ipykernel_26908\3670224332.py:2: DeprecationWarning: `method='interior-point'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  return sp.optimize.linprog(


179 ms ± 5.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
